spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# Make sure these email properties are pasted in this exact file!
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dummybrowser191@gmail.com
# CRITICAL: Make sure there are NO spaces in this password!
spring.mail.password=xeaqvlicojddeesq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
